version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
      - ./uploads:/app/uploads
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always